name: semantic
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2018.8.24=py35_1
  - cudatoolkit=10.1.243=h6bb024c_0
  - freetype=2.9.1=h8a8886c_1
  - intel-openmp=2020.1=217
  - jpeg=9b=h024ee3a_2
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - mkl=2020.1=217
  - ncurses=6.2=he6710b0_1
  - ninja=1.8.2=py35h6bb024c_1
  - numpy=1.14.2=py35hdbf6ddf_0
  - olefile=0.46=py35_0
  - openssl=1.0.2u=h7b6447c_0
  - pillow=5.2.0=py35heded4f4_0
  - pip=10.0.1=py35_0
  - python=3.5.6=hc3d631a_0
  - pytorch=1.5.0=py3.5_cuda10.1.243_cudnn7.6.3_0
  - readline=7.0=h7b6447c_5
  - setuptools=40.2.0=py35_0
  - sqlite=3.31.1=h62c20be_1
  - tk=8.6.8=hbc83047_0
  - torchvision=0.6.0=py35_cu101
  - wheel=0.31.1=py35_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
prefix: /home/fengsidong/miniconda3/envs/semantic

